<a href="https://colab.research.google.com/github/Akshat5129/Artificial-Intelligence/blob/main/Assignment_3_AU19B1023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CS6311 – Artificial Intelligence 
#Assignment 3: Recommender system 
###Co-Assignment - A (BookRental Recommendation System)
#Akshat Patel (AU19B1023)


###Tasks to be performed:

1. Read the books dataset and explore it.

2. Clean up NaN values

3. Read the data where ratings are given by the users.

4. Take a quick look at the number of unique users and books.

5. Perform data conversion for consistency.

6. Split your data into two sets (Training and testing)

7. Calculate the Similarity.

8. Use the evaluation metrics to make predictions.

###Datasets: 

1.   BX-Book-Ratings.csv
2.   BX-Books.csv
3.   BX-Users.csv

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df_user = pd.read_csv('BX-Users.csv',nrows =10000,encoding='latin-1')

In [4]:
df_books = pd.read_csv('BX-Books.csv',nrows =10000,encoding='latin-1')

In [5]:
df_books_ratings = pd.read_csv('BX-Book-Ratings.csv',nrows =10000,encoding='latin-1')

In [6]:
df_user

user_id                              Location   Age
0           1                    nyc, new york, usa   NaN
1           2             stockton, california, usa  18.0
2           3       moscow, yukon territory, russia   NaN
3           4             porto, v.n.gaia, portugal  17.0
4           5    farnborough, hants, united kingdom   NaN
...       ...                                   ...   ...
9995     9996  reynella, south australia, australia  29.0
9996     9997             willisburg, kentucky, usa  56.0
9997     9998                 warren, michigan, usa   NaN
9998     9999                beaverton, oregon, usa   NaN
9999    10000            jacksonville, florida, usa  38.0

[10000 rows x 3 columns]

In [7]:
df_user.describe()

user_id          Age
count  10000.00000  6273.000000
mean    5000.50000    32.415431
std     2886.89568    14.038664
min        1.00000     0.000000
25%     2500.75000    23.000000
50%     5000.50000    30.000000
75%     7500.25000    40.000000
max    10000.00000   239.000000

In [8]:
df_user.isnull().sum()

user_id        0
Location       0
Age         3727
dtype: int64

In [9]:
df_books

isbn                                         book_title  \
0      195153448                                Classical Mythology   
1        2005018                                       Clara Callan   
2       60973129                               Decision in Normandy   
3      374157065  Flu: The Story of the Great Influenza Pandemic...   
4      393045218                             The Mummies of Urumchi   
...          ...                                                ...   
9995   140283404  Beloved (Penguin Great Books of the 20th Century)   
9996   380730774  Read This and Tell Me What It Says : Stories (...   
9997   862418879                                     The Star Rover   
9998  340414645X                                   Die Keltennadel.   
9999  3442730988                                Tod in der Datscha.   

               book_author year_of_publication                   publisher  
0       Mark P. O. Morford                2002     Oxford University Press  
1     Richard Bruce Wright                2001       HarperFlamingo Canada  
2             Carlo D'Este                1991             HarperPerennial  
3         Gina Bari Kolata                1999        Farrar Straus Giroux  
4          E. J. W. Barber                1999  W. W. Norton &amp; Company  
...                    ...                 ...                         ...  
9995         Toni Morrison                2000               Penguin Books  
9996      A. Manette Ansay                1998              William Morrow  
9997           Jack London                2000             Canongate Books  
9998         Patrick Dunne                2001                    L�¼bbe  
9999       Anna Malyschewa                2003                         btb  

[10000 rows x 5 columns]

In [10]:
df_books.describe()

isbn                                       book_title  \
count       10000                                            10000   
unique      10000                                             9553   
top     195153448  The Golden Compass (His Dark Materials, Book 1)   
freq            1                                                5   

         book_author year_of_publication         publisher  
count          10000               10000             10000  
unique          5754                  63              1702  
top     Stephen King                2002  Ballantine Books  
freq              68                 919               300

In [11]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [12]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   isbn                 10000 non-null  object
 1   book_title           10000 non-null  object
 2   book_author          10000 non-null  object
 3   year_of_publication  10000 non-null  object
 4   publisher            10000 non-null  object
dtypes: object(5)
memory usage: 390.8+ KB


In [13]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [14]:
df_books_ratings

user_id        isbn  rating
0      276725  034545104X       0
1      276726   155061224       5
2      276727   446520802       0
3      276729  052165615X       3
4      276729   521795028       6
...       ...         ...     ...
9995      243   425164403       0
9996      243   440224764       0
9997      243   440225701       0
9998      243   440226430       0
9999      243   440234743       0

[10000 rows x 3 columns]

In [15]:
df_book = pd.merge(df_books_ratings,df_books,on='isbn')

In [16]:
df_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  
0                M. J. Rose                2002          Ballantine Books  
1              JOHN GRISHAM                2001                 Doubleday  
2              JOHN GRISHAM                2001                 Doubleday  
3            Dean R. Koontz                1996  Berkley Publishing Group  
4            Dean R. Koontz                1996  Berkley Publishing Group  
...                     ...                 ...                       ...  
1824  Kathleen E. Woodiwiss                1999                      Avon  
1825            Belva Plain                1998     Bantam Dell Pub Group  
1826            MARK HADDON                2003                 Doubleday  
1827          Jane Hamilton                1999    Anchor Books/Doubleday  
1828            Erich Segal                1998  Berkley Publishing Group  

[1829 rows x 7 columns]

In [17]:
df_book.nunique()

user_id                 465
isbn                   1366
rating                   11
book_title             1310
book_author             786
year_of_publication      42
publisher               313
dtype: int64

In [18]:
df_book.isnull().sum()

user_id                0
isbn                   0
rating                 0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [19]:
df_book.info

<bound method DataFrame.info of       user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Sil

In [20]:
df_book.describe()

user_id       rating
count    1829.000000  1829.000000
mean   240554.414434     3.088026
std     94802.011078     3.906933
min         2.000000     0.000000
25%    277195.000000     0.000000
50%    277884.000000     0.000000
75%    278418.000000     7.000000
max    278854.000000    10.000000

In [21]:
df_book.shape

(1829, 7)

In [22]:
df_book.corr()

user_id   rating
user_id  1.00000 -0.07885
rating  -0.07885  1.00000

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher'],
      dtype='object')

In [25]:
n_users=df_book.user_id.unique().shape[0]

In [26]:
n_books=df_book.isbn.unique().shape[0]

In [27]:
train_data,test_data=train_test_split(df_book,test_size=0.25)

In [28]:
train_data_matrix=np.zeros((n_users,n_books))

In [29]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
train_data

user_id        isbn  rating                               book_title  \
1067   278112   385472951       8                              The Partner   
105    276925   486282112       0     Frankenstein (Dover Thrift Editions)   
505    277427   345334019       0                         Escape the Night   
742    277523   684835983      10          Before I Say Good-Bye : A Novel   
229    277042  074343627X       8                             Dreamcatcher   
...       ...         ...     ...                                      ...   
1685       44   812523873       0                                  Proxies   
250    277261   440241073       7                              The Summons   
806    277639   425133540       0  The Sum of All Fears (Jack Ryan Novels)   
1672       19   375759778       7                         Prague : A Novel   
40     276828  2253044903       0      Le Parfum : Histoire d'un meurtrier   

                      book_author year_of_publication  \
1067                 John Grisham                1997   
105   Mary Wollstonecraft Shelley                1994   
505       Richard North Patterson                1995   
742            Mary Higgins Clark                2000   
229                  Stephen King                2001   
...                           ...                 ...   
1685               Laura J. Mixon                1999   
250                  John Grisham                2002   
806                    Tom Clancy                1996   
1672              ARTHUR PHILLIPS                2003   
40             Patrick S�¼skind                1988   

                          publisher  
1067                Doubleday Books  
105              Dover Publications  
505                Ballantine Books  
742            Simon &amp; Schuster  
229                          Pocket  
...                             ...  
1685                      Tor Books  
250         Dell Publishing Company  
806        Berkley Publishing Group  
1672  Random House Trade Paperbacks  
40                              LGF  

[1371 rows x 7 columns]

In [31]:
print(n_users,n_books)

465 1366


In [33]:
book_list=df_book.isbn.unique()

In [32]:
user_list=df_book.user_id.unique()

In [34]:
book_list


array(['034545104X', '038550120X', '425115801', ..., '385509456',
       '385720106', '425164403'], dtype=object)

In [35]:
user_list

array([276725, 276744, 278418, 276746, 277427, 278026, 276747, 278843,
       276754, 276964, 276755,     99, 276762, 276788, 278356, 276796,
       277195,    232, 276798, 277375, 276800, 278100, 276804, 276811,
       276904, 278314, 276822, 276828, 277681, 276832, 277143, 276837,
       276838, 276840, 278633, 276847, 276848, 276936, 276856, 276862,
       276866, 278778, 276869, 278251, 276872, 276875, 277712, 276878,
       276884, 276887, 276888, 276889, 277523, 277710, 276896, 278194,
       276911, 276925, 277623, 277413, 277439, 277752, 277965,    243,
       277589, 277648, 277689, 278137, 278221, 278390,     67, 276939,
       276954, 277042, 277157, 277378, 277478, 277530, 277932, 278176,
       278373, 278514,     14,    193,    242,     68, 276928, 276929,
       277253, 278162, 276953, 277743,     26, 276957, 278582, 278774,
       276984, 276986, 276988, 276989, 276994, 278563, 276998, 277009,
       277018, 277032, 277036, 277928, 277639, 278483, 278773, 278535,
      

In [36]:
def get_bookisbn_index(isbn):
    itemindex=np.where(book_list==isbn)
    return itemindex[0][0]

In [37]:
def get_userid_index(user_id):
    itemindex=np.where(user_list==user_id)
    return itemindex[0][0]

In [38]:
df_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  
0                M. J. Rose                2002          Ballantine Books  
1              JOHN GRISHAM                2001                 Doubleday  
2              JOHN GRISHAM                2001                 Doubleday  
3            Dean R. Koontz                1996  Berkley Publishing Group  
4            Dean R. Koontz                1996  Berkley Publishing Group  
...                     ...                 ...                       ...  
1824  Kathleen E. Woodiwiss                1999                      Avon  
1825            Belva Plain                1998     Bantam Dell Pub Group  
1826            MARK HADDON                2003                 Doubleday  
1827          Jane Hamilton                1999    Anchor Books/Doubleday  
1828            Erich Segal                1998  Berkley Publishing Group  

[1829 rows x 7 columns]

In [39]:
df_book['user_id']

0       276725
1       276744
2       278418
3       276746
4       277427
         ...  
1824       243
1825       243
1826       243
1827       243
1828       243
Name: user_id, Length: 1829, dtype: int64

In [40]:
df_book[['user_id','isbn']]

user_id        isbn
0      276725  034545104X
1      276744  038550120X
2      278418  038550120X
3      276746   425115801
4      277427   425115801
...       ...         ...
1824      243   380807866
1825      243   385316895
1826      243   385509456
1827      243   385720106
1828      243   425164403

[1829 rows x 2 columns]

In [41]:
df_book['user_id_index']=df_book['user_id'].apply(get_userid_index)

In [42]:
df_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher', 'user_id_index'],
      dtype='object')

In [43]:
df_book['book_id_index']=df_book['isbn'].apply(get_bookisbn_index)

In [44]:
df_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher', 'user_id_index', 'book_id_index'],
      dtype='object')

In [45]:
df_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  \
0                M. J. Rose                2002          Ballantine Books   
1              JOHN GRISHAM                2001                 Doubleday   
2              JOHN GRISHAM                2001                 Doubleday   
3            Dean R. Koontz                1996  Berkley Publishing Group   
4            Dean R. Koontz                1996  Berkley Publishing Group   
...                     ...                 ...                       ...   
1824  Kathleen E. Woodiwiss                1999                      Avon   
1825            Belva Plain                1998     Bantam Dell Pub Group   
1826            MARK HADDON                2003                 Doubleday   
1827          Jane Hamilton                1999    Anchor Books/Doubleday   
1828            Erich Segal                1998  Berkley Publishing Group   

      user_id_index  book_id_index  
0                 0              0  
1                 1              1  
2                 2              1  
3                 3              2  
4                 4              2  
...             ...            ...  
1824             63           1361  
1825             63           1362  
1826             63           1363  
1827             63           1364  
1828             63           1365  

[1829 rows x 9 columns]

In [46]:
df_book[['user_id_index','book_id_index']]

user_id_index  book_id_index
0                 0              0
1                 1              1
2                 2              1
3                 3              2
4                 4              2
...             ...            ...
1824             63           1361
1825             63           1362
1826             63           1363
1827             63           1364
1828             63           1365

[1829 rows x 2 columns]

In [47]:
train_data_matrix=np.zeros((n_users,n_books))

In [48]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [49]:
df_book.drop(['book_title','book_author'], axis = 1, inplace = True)

In [50]:
df_book.drop(['year_of_publication','publisher'], axis = 1, inplace = True)

In [51]:
df_book.drop(['user_id','isbn'], axis = 1, inplace = True)

In [52]:
df_book

rating  user_id_index  book_id_index
0          0              0              0
1          7              1              1
2          0              2              1
3          0              3              2
4          0              4              2
...      ...            ...            ...
1824       0             63           1361
1825       6             63           1362
1826       0             63           1363
1827       7             63           1364
1828       0             63           1365

[1829 rows x 3 columns]

In [53]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1371 entries, 1067 to 40
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   user_id              1371 non-null   int64 
 1   isbn                 1371 non-null   object
 2   rating               1371 non-null   int64 
 3   book_title           1371 non-null   object
 4   book_author          1371 non-null   object
 5   year_of_publication  1371 non-null   object
 6   publisher            1371 non-null   object
dtypes: int64(2), object(5)
memory usage: 85.7+ KB


In [54]:
train_data,test_data=train_test_split(df_book,test_size=0.25)

In [55]:
for line in train_data.itertuples():
    train_data_matrix[line[2]-2,line[3]-2]=line[1]

In [56]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 7.]])

In [57]:
train_data

rating  user_id_index  book_id_index
1731       7            438           1268
293        9            134            170
1593       2             34           1135
886        8            283            539
857        6            269            521
...      ...            ...            ...
1082       0             67            679
1348       0              2            907
356        0              4            207
443        0            191            251
1512       0              2           1064

[1371 rows x 3 columns]

In [58]:
from sklearn.metrics import pairwise_distances

In [59]:
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')

In [60]:
books_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [61]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [62]:
books_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [63]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis]) 
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])     
    return pred

In [64]:
books_prediction = predict(train_data_matrix, books_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [65]:
user_prediction

array([[ 0.04024619,  0.05748757,  0.04024619, ...,  0.04024619,
         0.04024619,  0.0553324 ],
       [-0.00670691,  0.01053447, -0.00670691, ..., -0.00670691,
        -0.00670691,  0.0083793 ],
       [ 0.16277869,  0.18006153,  0.16277869, ...,  0.16277869,
         0.16277869,  0.17790118],
       ...,
       [-0.00670691,  0.01053447, -0.00670691, ..., -0.00670691,
        -0.00670691,  0.0083793 ],
       [-0.00670691,  0.01053447, -0.00670691, ..., -0.00670691,
        -0.00670691,  0.0083793 ],
       [-0.00157141,  0.01566997, -0.00157141, ..., -0.00157141,
        -0.00157141, -0.00157141]])

In [66]:
books_prediction

array([[0.04688645, 0.04716068, 0.04688645, ..., 0.04688645, 0.04688645,
        0.04688645],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.16923077, 0.17022056, 0.16923077, ..., 0.16923077, 0.16923077,
        0.16923077],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00512821, 0.0051582 , 0.00512821, ..., 0.00512821, 0.00512821,
        0.        ]])